### ISSUE TITLE
* Required item displaying twice

### ISSUE THREAD

**Issue by frankjos** [organicinternet/magento-configurable-simple#10]
http://dawking.com/catalog/product/view/id/5977/s/hd-test/

as you can see, for some reason the (*required items) is displaying twice.

**Comment by toasty** [comment]
This is likely to be because your template is sufficiently different to the standard Magento ones that changes that SCP has made aren't quite working correctly. (eg Your template adds the message in a place that SCP doesn't know about)  

I'd suggest turning on 'template path hints', finding out which templates/blocks are responsible for outputting each '\* required items' and just removing one.

The one that's part of SCP is in app/design/frontend/base/default/template/catalog/product/view/options/scpwrapper.phtml

Matt

**Comment by frankjos** [comment]
Thank you, that worked perfectly. I am using this with Magento EE.

Awesome extension.
