### ISSUE TITLE
Problem with pricing showing wrong

### ISSUE THREAD

**Issue by luxico** [organicinternet/magento-configurable-simple#11]
Ive set this up on my site and it works well.  It shows the Price From £X depending on wht the lowest option is and if I add anything to the cart it adds the correct price based on that attributes price.  The only thing that appears wrong is that it shows the correct price from, say the lowest price attribute is £4, then it will say Price From £4.00.  However if you select any of the other attributes the Price From dissappears and it just says £4.00, even of the attribute is higher.  I would expect oit to show Price From £4.00 (or whatever the lowest price is), then if you choose a higher priced attribute it will remove the Price Fom and show the actual price (whatever that may be)

**Comment by toasty** [comment]
Hello,

The way is should be working is:
- The 'price from' text should only disappear once all remaining associated products all have the same price.
- The displayed price should be the lowest price of any of the remaining associated products all have the same price.
  (as you pick options it narrows which possible associated products can be selected via the subsequent options)

So if you've picked all your options there's only 1 possible product left, so the 'price from' should disappear and the price that shows should be that of that associated product.

I suspect something might be causing a JS error so the code which updates the price itself isn't running.

Specifically one thing I've seen a few people do is remove one of the displayed prices which the Magento js (and therefore SCP) needs in order to be able to update the price.

To check - within a &lt;div class="price-box"&gt; you should have a &lt;span id="configurable-price-from-YOURPRODUCTID"&gt; 
If you only have one which is elsewhere on the page which looks the same but has _clone on the end of the id, eg:  &lt;span id="configurable-price-from-YOURPRODUCTID_clone"&gt; you'll still see a price on the page but Magento's JS will break.

If you can, install firebug and see if you're getting JS errors.

Matt

**Comment by toasty** [comment]
Of for crying out loud, github has stripped the html, thanks github!
I'll see if I can get something to show by tarting with markdown....

**Comment by toasty** [comment]
Closing as it's old now and it's an unconfirmed issue. (It can always be reopened if need be.)
