### ISSUE TITLE
showing a loading icon on the div that contains the image and the gallery

### ISSUE THREAD

**Issue by alain57** [organicinternet/magento-configurable-simple#16]
This plugin is great, but the ajax call to change the image and image gallery can take some time.
between 2 and 10 seconds depending on the server hardware (from my testings)
I don't think that customers will wait 10 seconds to see changes...

so i guess it would be best to add a loading image when the dropdown box is changed, the ajax call will replace the content and remove the loading picture

**Comment by toasty** [comment]
Hiya - 10 seconds seems a very long time. It takes at most 1 second for me when it's just running on my desktop. (which is 2.16GHz Core 2 duo or something) 
As far as I know it's not doing anything special, just using the block/template that the normal product page would.  In the case where it takes 10 seconds, how long do normal Magento pages take to load?

Also there's a basic 'loading' message you can enable by uncommenting a line in scp_product_extension.js  Look for the comment in the code which says:
    //Uncomment the line below if you want an ajax loader to appear while any custom
    //options are being loaded.

but that just puts a message down near the configurable options, and waits for the other ajax call which loads in any tier prices and custom options, rather than the image specifically, though it would be easy to move to the other call.

If you want it to do something better, how about, off the top of my head, in the showFullImageDiv function adding the following which will make the images fade out until the new ones are loaded, so that the customer can see something's happening at least:

after 
    if(productId) {
add
        $$('div.product-img-box').each(function(el) {
            el.fade({ duration: 0.3, from: 1, to: 0.5, queue: 'end' });
        });

after:
       onComplete: function() {
add:
                    $$('div.product-img-box').each(function(el) {
                        el.fade({ duration: 0.3, from: 0.5, to: 1, queue: 'end' });
                    });

You can add extra messages to that etc - but hopefully it's a useful start.

**Comment by toasty** [comment]
.
