### ISSUE TITLE
Changing the "Price From" tag after the selection has been made

### ISSUE THREAD

**Issue by cwpollock** [organicinternet/magento-configurable-simple#8]
Currently it looks like it sets the SPAN to blank when the final selection has been made.  I was thinking of putting some text in there like "Your Price".  I thought changing line 70 of this file would do the trick : http://github.com/organicinternet/magento-configurable-simple/blob/master/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Block/Product/View/Type/Configurable.php 

But that doesn't seem to work.  Any hints on how to change this?

**Comment by toasty** [comment]
That bit of code is actually run as the part of the product page generation and the logic is:  if highest price for any of the associated products is the same as the lowest, pass through '' to the JavaScript instead of 'Price From:'. (as there's no point in saying 'Price From' if all possible prices are the same)

To do what you're after you could change the following in scp_product_extension.js:

From:

```
Product.OptionsPrice.prototype.reloadPriceLabels = function(productPriceIsKnown) {
    var priceFromLabel = '';
    var prodForm = $('product_addtocart_form');

    if (!productPriceIsKnown && typeof spConfig != "undefined") {
        priceFromLabel = spConfig.config.priceFromLabel;
    }
```

to:

```
Product.OptionsPrice.prototype.reloadPriceLabels = function(productPriceIsKnown) {
    var priceFromLabel = '';
    var prodForm = $('product_addtocart_form');

    if (typeof spConfig != "undefined") {
        if (productPriceIsKnown) {
            priceFromLabel = "Your price:"; //should really pass this in from getJsonConfig
        } else {
            priceFromLabel = spConfig.config.priceFromLabel;
        }
    }
```

**Comment by toasty** [comment]
.
